baseURL = 'https://hemanth7040.github.io/'
languageCode = 'en'
title = 'Hemanth Kumar Motukuri'
theme = 'blowfish'
defaultContentLanguage = "en"


[taxonomies]
  category = "categories"
  tag = "tags"
  project = "projects"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



