[[main]]
  name = "Blog"
  pageRef = "categories"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "contact.md" # Points to content/contact.md
  weight = 40