[[main]]
  name = 'DevOps'
  pageRef = 'categories/devops'
  weight = 5 

[[main]]
  name = 'Kubernetes (CKA)'
  pageRef = 'categories/kubernetes'
  weight = 10

[[main]]
  name = 'Terraform'
  pageRef = 'categories/terraform'
  weight = 20

[[main]]
  name = 'Docker'
  pageRef = 'categories/docker'
  weight = 30

[[main]]
  name = "Resume"
  pageRef = "/resume" # Points to the webpage
  weight = 30