[homepage]
  layout = "profile"
  showAuthorBio = true  # The switch must be ON here
  showRecent = false

[params]
  customCSS = ["css/custom.css"]

[article]
  showTaxonomies = true

[taxonomy]
  layout = "term-grid"
  showTermCount = false
  cardView = true